### ISSUE TITLE
GeoData API Technical Requirements

### ISSUE THREAD

**Issue by aashish24** [ResonantGeoData/ResonantGeoData#17]

**Comment by aashish24** [comment]
- We will need to support temporal component
- 3D mesh data needs to be supported in the future

**Comment by manthey** [comment]
For reference: https://github.com/OpenGeoscience/girder_geospatial

**Comment by banesullivan** [comment]
I have been looking into what GeoDjango can handle and it's pretty compelling - I've been taking some notes and want to try some things out before I report too much else here. In brief, GeoDjango is a Django interface to PostGIS with support for vectorized data (shapefiles) and raster imagery where these data are typically static (no time variance) all implemented over GDAL.

------

In the meantime, I have been thinking a lot about how we can approach handling temporal data when working with rasters and how we need to be aware that down the road we will also need to support 3D data. A significant challenge arises when implementing a "model" to handle temporally varying remote sensing (RS) data: temporally varying data is most often also spatially varying in RS, however in my experience temporal 3D data is typically spatially static and only the data/values that live on the mesh are varying. 

For example, take any path and row of Landsat 8 imagery that you're interested in (e.g. Path 34 and Row 32 for Golden, CO) and query available data through time for that tile. You'll notice that the path shifts through time though our ROI (Golden) is in each of the tiles at different parts of the image:

![Screen Shot 2020-05-08 at 4 07 31 PM](https://user-images.githubusercontent.com/22067021/81445654-4ab06080-9147-11ea-8778-f8c7e4a99b98.png)


Currently, we can work with this by simply storing each raster in the DB individually with a timestamp and querying all rasters through time based on a specific area of interest. This is what it seems just about everyone else does when dealing with time-varying RS data. And it is an easy, somewhat lightweight solution as rasters are just images - the geometry to define them is nothing more than coordinates of the origin, pixel sizes, and pixel extents. So it is unlikely these elements will be repeated across your spatiotemporally varying data.

However, this sort of "model" might conflict with an approach to handle temporally varying 3D data where the geometry/extent of them does not change (spatially static). In this case, the dataset itself may contain a time-varying field but the geometries will not change through time. For example, a 3D model of contaminant transport in the subsurface where the mesh/spatially domain is constant, but the field values change through time:

*<😞, I can't immediately find a cool GIF for this>*

This makes me wonder what would be the best way to approach implementing a model framework that can handle both time-varying 2D data (rasters) and time-varying 3D data (physical models, etc). So far where I am at is:

Implement the raster models as is like GeoDjango has it just with a timestamp as the spatial variance is easy to deal with in those cases. Then for 3D data have a model very similar to the base model for rasters that has a field for pointing to a bare mesh and another field pointing to data that can populate that mesh (as the data is typically dynamic and the mesh is typically static). This approach will enable us to point model entries to the same mesh when the mesh is static or be able to have 3D that varies in space and time as well.

----

My next steps: try to get up and running with GeoDjango and create a simple web app that can query a DB for time-varying rasters of an ROI as well as a proof-of-concept "model" for 3D data that points to separated mesh/data files.

Note: I will likely stick with a VTK format for the 3D data to keep things simple, but we may want to think about how to disconnect data from the mesh so that we can have a mesh file and a separate data field file. Any suggestions on a preferred format for this? There are a lot of approaches to this.

**Comment by banesullivan** [comment]
Following up from our meeting this morning. Here are some key points about the GeoData API that is in the works.

cc @aashish24, @manthey 

I have a basic Django app working that I still need to push to a branch in this library once #39 is completed

### Description
We are working towards a "data catalog" (GeoDataAPI) that has extract-transform-load/store (ETL/S) pipelines, facetted searching, and standardized serving for geospatial information. This data catalog will support traditional geospatial data types (raster and vector data) with a roadmap to support other geospatial-esque data down the road (aerial videos, 3D data, etc.).

### High-level goals
- Be able to index and search data by:
	- geometry type, location, time, acquisition params, data types (RGB, hyperspectral, etc.), spatial references, resolution, extents, sensor type, sensor location (edge case)
- Provide a REST API to enable users to quickly:
	- Perform a facetted search (e.g. acquisition system or spatial extents)
	- Download data in bulk 
	- Stream data to client
	- Export data in different OGC data standards (for rendering/vis)
	- Perform subsampling and/or cropping of data
- Create a Python API that can access the REST API
- Store and serve the data in a standard/format that is useful to our clients and general machine learning/analytics workflows.
	- Data serving routines with the COG format
- Provide a basic front end to the Django application for searching, visualizing, and downloading these data on the web
- Interface to existing technologies and software to provide wide support for computing ecosystems
- Team goals:
	- To learn as much as we can about what it takes to implement this type of technology and where the challenges are
	- To position ourselves with a new skillset for deploying a geospatial "data catalog" across Kitware projects.


### Data types to support
- [x] First Stage: general raster and vector data with associated meta info
- [ ] Second Stage: specific raster data types from known acquisition systems (e.g. storing addition meta info for Landsat 8 specific data)
- [ ] Third stage: additional data types with associated geospatial references like aerial videos and 3D subsurface data

### Potential Challenges
- What should our ETL routines look like? Should we establish a single standard data format for serving the data? Do we want to use COG?
	- We need to make sure we aren't restoring the same data
	- Note that GeoDjango stores the GDAL raster by pointing to the raster file and knowing which GDAL driver to use - should we have the ingestion routines convert everything a specific standard that GDAL also supports so that we can store and serve the data in the same format?
- We need to keep in mind that this tool shouldn't become "too general" - it should have a clear focus, target user base, and goal-oriented approach to feature development
	- This is a "GeoData" API, not a "data" API - keep it geared towards geospatial data

**Comment by aashish24** [comment]
@banesullivan thanks for organizing our discussion in a well documented issue. I believe your text covers everything that we discussed. Is there anything else you need feedback on?

**Comment by banesullivan** [comment]
at the moment, no need for further feedback.

I'll need help getting the prototype GeoData app I've created pushed into this repository and @brianhelba, @manthey, and I will need to discuss what I've implemented there, how it addresses the points in this issue, and make sure we are following best practices for the models.

**Comment by aashish24** [comment]
@banesullivan @manthey few things: 

@banesullivan it would be great if you could add these to the requirements: 
1) GeoData enabling users to store data into GeoTiff/NumPY or XArray/Zarr format
2) We need to scale test the test - we want to store upto PB size data
3) @manthey it would be great if we are the first implementor of new OGC WMTS API. See here: https://github.com/opengeospatial/OGC-API-Tiles

**Comment by manthey** [comment]
There are two totally separate things to be scaled for large amounts of data.  Datasets themselves could be very large OR you can have a LOT of datasets.  For large datasets, if the dataset is well formatted, you just need to have decent storage: for instance, a geotiff covering the entire earth at 1m could easily take up the better part of a petabyte.  For numerous datasets, you need to have an efficient database: for instance, if you have a billion records, doing a geospatial search might require partitioning that database based on likely query parameters.

Using Postgres and S3 at least has to potential to scale either of these as needed.  Until we start seeing performance issues, it will be hard to optimize for what actual use cases will be.

On a project I worked on a decade ago, we generated synthetic data that had characteristics matching certain properties of our actual data (we called it the large dull collection) so that we could optimize for certain use cases: ingest speed, look up speed, etc.  One approach is to get a sampling of representative data and then generate a synthetic dataset from that for testing.

**Comment by banesullivan** [comment]
> GeoData enabling users to store data into GeoTiff/NumPY or XArray/Zarr format

We can implement data ingestion routines for those formats, but storing them may not be redundant. GeoDjango's [`GDALRaster `](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/gdal/#django.contrib.gis.gdal.GDALRaster) entry will hold the data in the database so once the user uploads data in those formats and we create the model entry, the data is effectively converted and re-stored.

We can create raster entries from files (any format that has a driver in GDAL), packed strings, buffers, and NumPy arrays so creating a DB entry from those formats should be easy ([see this](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/gdal/#creating-rasters-from-data)) **but do you want to actually "store" those formats?** Or would it be okay to have routines for accepting those data types into the DB, but not storing them? Then we could have the Python API we intend to create be the layer that can fetch data from the GeoData API endpoints and hand it of to a user in xarray (etc.) formats/data structures.

**Comment by aashish24** [comment]
> The OGC-API-Tiles API is still very much a work in progress (e.g., "This standard defines TBD requirements / conformance classes."). It looks like a superset of the way we serve raster tiles via large_image with the addition of some standardized ways to aid in discoverability. This is a separable issue from the GeoData API requirements, so I'll create a new issue for discussing this

@manthey that is correct, it is work in progress. I talked to the lead person from OGC and he said that it is probably a good time to implement something based on what they have. There could be two advantangeous: 1) we will be the first few ones that will get it done and may help us with our business 2) OGC itself could use what we create - he said that he will be happy to use such implementations for testing - so better cooperation with OGC is a possibility 3) eventually everything will move to it. 4) I think the API is so much better than before. What do you think?

**Comment by aashish24** [comment]
> We can implement data ingestion routines for those formats, but storing them may be redundant. GeoDjango's [`GDALRaster `](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/gdal/#django.contrib.gis.gdal.GDALRaster) entry will hold the data in the database so once the user uploads data in those formats and we create the model entry, the data is effectively converted and re-stored.

That is a good point. I was thinking that we will not store the converted data in database but rather on the filesystem and have a pointer for it in the database but not the data itself. Thoguhts?

**Comment by manthey** [comment]
> @manthey that is correct, it is work in progress. I talked to the lead person from OGC and he said that it is probably a good time to implement something based on what they have. There could be two advantangeous: 1) we will be the first few ones that will get it done and may help us with our business 2) OGC itself could use what we create - he said that he will be happy to use such implementations for testing - so better cooperation with OGC is a possibility 3) eventually everything will move to it. 4) I think the API is so much better than before. What do you think?

It actually doesn't look too complicated.  It should be straightforward to do this as part of making our Django app a tile server for formats we know how to serve.  Initially, my first pass would use large_image to server raster tiles and expose the appropriate endpoints via swagger (see PR #60 for adding swagger easily).

**Comment by manthey** [comment]
In large_image, we have the ability to convert some formats that we can't serve directly into a format we can.  This adds some maintenance burden for the conversion, adds time to the ingest, and risks ignoring some data that a better reader might be able to handle (e.g., a multi-stack tiff ends up with just one image).  However, data we convert ends up being very efficient to serve.

For rasters, I think we initially want to do the same things: if we can read it directly (via gdal and/or mapnik), we don't alter it.  One format that large_image reads that I don't know how GeoDjango handles is netcdf (it can have different resolutions and extents per subdataset).

I think we want to avoid any data conversion IF we can already read and serve the data.  If we find that we are serving data and it is inefficient, then we should consider whether speeding up serving the data is less work than maintaining converted data.  Similarly, if we have common formats that we want to serve and GeoDjango or large_image can't read, it might be worth adding handlers for those formats rather than doing the conversion.  Avoiding initial conversion makes ingest faster and maintenance easier at the expense of reader complexity.

**Comment by banesullivan** [comment]
I posted a brief description of the current ETL routine in https://github.com/ResonantGeoData/ResonantGeoData/issues/66#issuecomment-641366619. I want to expand on that here...

With the ETL routine storing the data in a single standard, we could now build up an API around that standard so that we do not need to maintain many routines across our API for handling all of the different formats in which a user could upload the data. Then for specific user needs, we could create a new ephemeral model (perhaps called `RasterExported`) that will export rasters to known formats (and store that file on the file system). We could then serve out that exported format on-demand and automatically purge these entries after X amount of time (or some other criteria like usage statistics). We could also incorporate some checking in our ETL routine to see if the original uploaded format is in one of the common export formats and if so, store it as such.

This would enable us to expand the geodata API out around a single standard and still meet user needs (e.g. the data was uploaded in a xarray/NetCDF file but a user wants to pull it down as a GeoTIFF and our API wants to work directly with PostGIS). With this sort of infrastructure, we would have a way to build pipelines for any type of remote sensing data - storing it in PostGIS, serving it out in different formats for downstream needs, and having a clear and easily maintainable toolkit built around a single standard interfacing with PostGIS via GeoDjango.

The concern I have for our database pointing to data in its original format is that we might have to maintain a lot of code across the geodata API to handle all the different formats and that our API may become fragmented. For example, I imagine there being an odd format we are asked to support down the road. Then someone writes the ingestion code to create models for that format but doesn't write the needed code to support that format for an ML pipeline we have built around the API - thus some parts of the API support that format but not others and the toolkit becomes fragmented for that user.

**Comment by banesullivan** [comment]
Also, as https://github.com/ResonantGeoData/ResonantGeoData/issues/64#issuecomment-641391416 points out, leaving the data in its raw format can lead to problems when multi/hyper-spectral data is stored in a file series rather than as a single, multi-band raster. Having our ingestion routine aggregate those separate rasters into a single entry would clean this up

**Comment by aashish24** [comment]
> With the ETL routine storing the data in a single standard, we could now build up an API around that standard so that we do not need to maintain many routines across our API for handling all of the different formats in which a user could upload the data. Then for specific user needs, we could create a new ephemeral model (perhaps called `RasterExported`) that will export rasters to known formats (and store that file on the file system). We could then serve out that exported format on-demand and automatically purge these entries after X amount of time (or some other criteria like usage statistics). We could also incorporate some checking in our ETL routine to see if the original uploaded format is in one of the common export formats and if so, store it as such.

Yeah, I like this idea. I guess the question would be is storing the data i the database is a must have or configurable? Also what are the cons of that approach? Specifically I think in our case there is a strong possibility that users want to store actual bytes on the S3 or other cloud storage system (managed or not).

**Comment by aashish24** [comment]
> The concern I have for our database pointing to data in its original format is that we might have to maintain a lot of code across the geodata API to handle all the different formats and that our API may become fragmented

May be - If we use some common library (such as GDAL) than it does not really matter as much because all we see if GDAL data structures, we would just need to pass the options on what format we need when we export.

**Comment by manthey** [comment]
I think that whether we convert to a standard format on ingest or handle multiple formats depends on where the original data is located and how often it gets accessed.

We have a number of projects with federated data (data stored in external storage where we can query what data exists but not modify it).  In those, the data volumes can be large, and duplicating (and converting) the data has a real cost in both time and storage.  It is often possible to catalog such data relatively cheaply, and then only fetch the bulk of the data on actual demand.

In some microscopy projects, it is often handy to connect to a new asset store (such as a shared file system) and start viewing the data right away.  Here the ability to have a viewer that can handle multiple formats gives a much more responsive experience than would be possible if all of the data needed conversion first.  The viewer is less efficient on many of these formats, but it saves the conversion time, so it is more performant for certain use cases.

We might have an ETL step that learns the format of the data but does not convert it unless and until it is actually requested.

**Comment by banesullivan** [comment]
Closing due to staleness, the progress that completed these tasks, and other open issues that are reworking this
