### ISSUE TITLE
Static resources different on deployment

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#210]
It appears the static resources are set to something different when using the deployment settings. 

There is a deployment error from the stylesheet not being found. The dev settings work though.

Where is this set in the deployment configuration?

**Comment by jbeezley** [comment]
You might need to include the static files in python package like in https://github.com/girder/django-composed-configuration/pull/82.

**Comment by brianhelba** [comment]
> You might need to include the static files in python package like in [girder/django-composed-configuration#82](https://github.com/girder/django-composed-configuration/pull/82).

I don't believe this resolves the issue. Heroku pulls the project source directly from Git, not a packaged sdist. On deployment, the Heroku buildpack runs `setup.py develop` to install requirements, which does not package or install the project itself.

As a general practice, we do not need to make Django projects packageable.

---

This issue can be reproduced locally just by running `./manage.py collectstatic`. In typical development, static files are configured to be served directly from their existing locations, so `collectstatic` is not necessary.

**Comment by brianhelba** [comment]
The actual bug in this case seems to be in the file https://github.com/ResonantGeoData/ResonantGeoData/blob/master/rgd/core/static/css/style.css :
```
@import url('rgd/base.css'); /* fonts, links, headings, structure */
```

This would expect to find a file at one of:
* `rgd/core/static/css/rgd/base.css`
* `rgd/geodata/static/css/rgd/base.css`

but no such file exists. Note that since the referencing file is already within `css/`, the `@import` lookup will yield a path relative to that.

---

It's a Django best practice to re-namespace all content in `templates` and `static`, since Django concatenates all apps' directories together during lookup. For example, a `foo.css` file in the `core` app ought to live at `rgd/core/static/core/css/foo.css`.

As part of a fix, I would suggest moving the content of the `rgd/core/static` directory to `rgd/core/static/core` instead. That should make static file lookups less semantically ambiguous in the future.

**Comment by jbeezley** [comment]
> I don't believe this resolves the issue. Heroku pulls the project source directly from Git, not a packaged sdist. On deployment, the Heroku buildpack runs setup.py develop to install requirements, which does not package or install the project itself.

Just to clarify, the package data config is necessary whether or not you are installing from an sdist, *if* you are installing to site-packages.  In fact, the changes in https://github.com/ResonantGeoData/ResonantGeoData/pull/212 are not sufficient for installing from an sdist as you need to include them in the manifest as well.

If heroku does a development install, then yes, #212 won't change anything, but I think it's a good idea regardless.

**Comment by banesullivan** [comment]
> If heroku does a development install, then yes, #212 won't change anything, but I think it's a good idea regardless.

Let me know if I should reopen that PR.

In the meantime, I will create a new PR to resolve the issue in https://github.com/ResonantGeoData/ResonantGeoData/issues/210#issuecomment-744507473 and move the files around to follow Django conventions

**Comment by brianhelba** [comment]
> If heroku does a development install, then yes, #212 won't change anything, but I think it's a good idea regardless.

I agree. Heroku only requires a `requirements.txt` at a minimum, but using setuptools is nice to add extra metadata and gives us the option to publish packages if desired.

@jbeezley Could you create a PR at https://github.com/girder/cookiecutter-django-girder to add the extra necessary fields, and we can pull it back down to all projects from there?
