### ISSUE TITLE
field_file_to_local_path runs out of disk space with large images

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#225]
When importing a large image/raster (1.68 GB), the file system runs out of memory (ran locally via Docker).

We should see if we can do these transforms without regenerating the raster, OR do the subsampling for the thumbnail before/during the transform to prevent us from running out of memory.

The problem data: [`elevation.tif`](https://data.kitware.com/#item/5dbc4f66e3566bda4b4ed3ad)

**Comment by banesullivan** [comment]
It appears the memory runs out during the call to `field_file_to_local_path`

**Comment by banesullivan** [comment]
I think the best solution here would be to downsample the original raster to some max resolution (like we already do when fetching a thumbnail) and using that for all of our metadata, geometry, and thumbnail extraction. This would need to be done for all `ImageFile`s and perhaps stored in that model.

Somehow, we will need to do this without using `field_file_to_local_path`.

**Comment by brianhelba** [comment]
I'm not totally clear whether the issue is disk space or memory, since the terms are used somewhat interchangeably. It seems like it's actually disk space?

Is this only happening in local development, inside Docker, or are we seeing this on production too? Heroku should provide more temporary space than just 2GB.

This might be an easy fix, since disk space generally should be abundant and cheap. I'm happy to talk about it.

**Comment by brianhelba** [comment]
Looks like the problem was a locally-applied limit on Docker's total disk usage.

**Comment by banesullivan** [comment]
Yep, the problem was disk space allocations locally for Docker.

This brings up another issue: the fact that we are downloading entire files locally when we need to use GDAL to extract metadata. While this isn't a breaking issue, it is wildly inefficient and we should come back to this to see if we can implement  some sort of FUSE mount to the storage container from the worker's file system
