### ISSUE TITLE
Support non-rectangular bounding box in SpatialEntry `footprint` or `outline`

### ISSUE THREAD

**Issue by matt-bernstein** [ResonantGeoData/ResonantGeoData#372]
`SpatialEntry.footprint` and `SpatialEntry.outline` seem to be identical in every `RasterMetaEntry` I have downloaded. I am not sure what the difference is supposed to be. The following is a use case that should be supported in whichever one of them `search` checks.

A query for `{'type':'Point','coordinates':[128.6643, 37.6601]}`, `instrumentation='OLI_TIRS'` (Landsat-8) in RGD looks like this:
![image](https://user-images.githubusercontent.com/60152561/116109499-d554dd00-a682-11eb-9931-a1b1b8d627dd.png)

But the Landsat path-row that covers that point (enter same coordinates into https://landsat.usgs.gov/landsat_acq#convertPathRow) looks like this:
![image](https://user-images.githubusercontent.com/60152561/116109690-07fed580-a683-11eb-8c30-6db3a3307c42.png)

because the Landsat WRS-2 coordinate system is offset from the standard projection (EPSG 4326?) that RGD uses.

It seems that during ingestion into RGD, the EPSG4326/WGS84 bounding box of the scene is used as `footprint` and `outline`. But the true outline can be found in the files:

```bash
$ grep 'LAT_PRODUCT\|LON_PRODUCT' LE07_L1TP_115034_20181102_20181129_01_T1/LE07_L1TP_115034_20181102_20181129_01_T1_MTL.txt
    CORNER_UL_LAT_PRODUCT = 38.43903
    CORNER_UL_LON_PRODUCT = 126.71531
    CORNER_UR_LAT_PRODUCT = 38.46006
    CORNER_UR_LON_PRODUCT = 129.54100
    CORNER_LL_LAT_PRODUCT = 36.49358
    CORNER_LL_LON_PRODUCT = 126.77379
    CORNER_LR_LAT_PRODUCT = 36.51319
    CORNER_LR_LON_PRODUCT = 129.52714
```
(There are probably more reliable ways to do this... I will dig around some more. [This](https://gis.stackexchange.com/questions/372160/issue-while-creating-dataset-mask-for-landsat-7-etm-band-data-by-using-rasterio) could be a good starting point.)

The reason this is a problem is that it could cause false positives in a search for those triangular spatial regions outside the path-row but inside the bbox. However, this is not a fundamental flaw because a user who knows to look for a `nodata` mask can correct for this after downloading the images.

So there are several action items here:
1. Allow nonrectangular bounding box in `SpatialEntry` - does any work need to be done for this?
2. For Landsat specifically, read the valid data mask or the path-row in the shapefile to get the true footprint
3. For all satellites, handle reboxing correctly when converting from source CRS to RGD's CRS (in which the rectilinear bbox from the source CRS becomes diagonal)

**Comment by matt-bernstein** [comment]
I found the right terminology for this - it's a [reboxing](https://gis.stackexchange.com/a/244565) issue

**Comment by banesullivan** [comment]
> `SpatialEntry.footprint` and `SpatialEntry.outline` seem to be identical in every RasterMetaEntry I have downloaded. I am not sure what the difference is supposed to be

This is intentionally set by default. The `outline` is typically the bounding box (rotated or not) of the spatial entry and `footprint` is typically a valid data mask. Computing the valid data mask is almost always an expensive operation (requiring us to download the entire image data) and thus we have disabled it on ingestion. This is why `footprint` is set to be the same as `outline` by default (to skip the valid data mask processing step to greatly speed up ingestion times). There is an admin action to compute the valid data footprint though I have noticed it not always working lately.

----

> 1. Allow nonrectangular bounding box in SpatialEntry - does any work need to be done for this?

Any Polygon geometry can be used for either the `outline` or `footprint` fields in `SpatialEntry`, so there is no action needed to "allow this"

> 3. For all satellites, handle reboxing correctly when converting from source CRS to RGD's CRS (in which the rectilinear bbox from the source CRS becomes diagonal)

I will jump on this. It should be a quick fix

> 2. For Landsat specifically, read the valid data mask or the path-row in the shapefile to get the true footprint

I will handle this last and see if 3 can actually address this.

Further, since the valid data mask routine isn't always working, I will take a look at that while dong this work to see if I can fix that.

**Comment by banesullivan** [comment]
> > 3. For all satellites, handle reboxing correctly when converting from source CRS to RGD's CRS (in which the rectilinear bbox from the source CRS becomes diagonal)
> 
> I will jump on this. It should be a quick fix

This is actually what this code is supposed to be doing:

https://github.com/ResonantGeoData/ResonantGeoData/blob/f061448eba6887c60fa4c1ce2190b74782ae7b94/rgd/geodata/models/imagery/etl.py#L130-L144
