### ISSUE TITLE
Heat map to show all data in the catalog

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#389]
We should add a new heatmap page to show a heat map of all of the data in the catalog.

It would be nice to also show this heatmap during the search, but I'm not sure how best to handle that since we do want the footprints of the paginated search results to show up too

**Comment by manthey** [comment]
We did a heatmap in a Girder 3 plugin (https://github.com/girder/girder-geo-heatmap).  If memory serves, for each geospatial entry, it computed the average of the boundary points and used that point on the heatmap.  It was slow because it fetched all of the data via the client (no server-side request to get the points).

**Comment by banesullivan** [comment]
Thanks, David! this is really useful!

I think I am also going to include other broad stats about the data catalog (such at temporal ranges, number of each type of entry, etc) on one page under the `/stats/` path with this heatmap
