### ISSUE TITLE
Use memcached with large_image

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#554]
Right now, large_image is using Python memory for caching per process (large_image logs `Using python for large_image caching` anytime we request tiles). This means the cache is not actually being used when serving tiles as each request comes in through a different process.

We need to configure large_image to use Memcached:

```py
large_image.config.setConfig('cache_backend', 'memcached')
```

This requires a memcached server running somewhere - we may need this in both the django and celery services. My current impression is that different services (on different nodes/machines) cannot share a cache

**Comment by manthey** [comment]
memcached can be configured on a separate machine using the config settings `cache_memcached_url` (defaults to `127.0.0.1`), `cache_memcached_username`, and `cache_memcached_password`.  This is only useful if network access to the memcached server is faster than tile access from the source files.

**Comment by banesullivan** [comment]
Thanks for the tip, @manthey! I'm curious what exactly the keys are for the cached tiles? Are the keys, the file path (and open parameters like `projection`)?

I'm wondering if we could have our web server and our worker share a memcache server for the tiles and if that's possible - I suppose this means we will have to have a predetermined path that is consistent across servers (e.g. `/tmp/rgd/file_cache/...`.

**Comment by manthey** [comment]
The code in Girder 3 is here: https://github.com/girder/large_image/blob/0a29523923106f079c35b6de6cf7e9e04aea4434/girder/girder_large_image/models/image_item.py#L192
Fundamentally, we know we record what tile source was sued (gdal, openslide, etc).  From that, the hash is taken from the source classes hash (based on the path and the options such as projection and style), plus a string hash based on the tile parameters.

So, yes, you'd want a consistent path across servers OR you'd need to redefine how the class hashes are generated (so it uses, for instance, the primary key from the django table instead of the path).
