### ISSUE TITLE
Deprecation Policy

### ISSUE THREAD

**Issue by Erotemic** [ResonantGeoData/ResonantGeoData#602]
It looks like rgd_client.rgdc.RasterDownload was removed and after about 45 minutes of investigation I figured out it now lives in a different module: `rgd_imagery_client`.

While reorganization like this is probably for the best, it would help end-users like myself if there was some sort of deprecation warning when something like this occurred in the future. It would be fine if this worked in Python 3.7+ only, because they you could just define a module level `__getattr__`.

It could be as simple as

```python

def __getattr__(key):
    if key == 'RasterDownload':
        raise Exception('RasterDownload was moved to rgd_imagery_client.RasterDownload, please use that instead')

```

Of course, an even nicer solution might do something like 

```python

def __getattr__(key):
    if key == 'RasterDownload':
        import warnings
        warnings.warn('RasterDownload has moved to rgd_imagery_client.RasterDownload, please use that instead. This warning willl become an error in version X.Y.Z', DeprecationWarning)
        from rgd_imagery_client import RasterDownload
        return RasterDownload
    else:
        raise AttributeError

```

where it warns the user that deprecation is about to happen, but it still functions for a few more versions.

Something along these lines would help smoothly transition between versions.

**Comment by banesullivan** [comment]
Hey @Erotemic, I understand your frustration with the rapidly changing API and lack of deprecation warnings. Unfortunately, we are moving rapidly and we are just now getting to a point where we can call the API "stable" -- a cost of this rapid movement is a lack of deprecation warnings when things change.

Moving forward, we will include deprecation warnings in the Python client as we are now reaching a point of "stability". 

To mitigate this in the future, let's implement some tests specific to your workflow and specific to how RGD is being used in WATCH so that we catch these issues upstream before you see them.

Further, please reach out directly to me or @AlmightyYakob next time you run into an issue with the Python client since you/WATCH are our primary users.

**Comment by banesullivan** [comment]
Moving forward, we will work to include deprecation errors. That's the new policy, thanks for bringing this up.

@AlmightyYakob, please keep this in mind moving forward
