### ISSUE TITLE
Improve raster STAC endpoint

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#669]
Currently, to retrieve the STAC Item JSON for a raster, you must know the collection ID of the raster. This isn't very user-friendly and we are more than able to add a new endpoint that enables users to request a STAC Item for a raster without knowing its  collection.

For https://github.com/ResonantGeoData/RGD-Vue/issues/82 and #653 

The following demonstrates how a user currently must do this:

https://github.com/ResonantGeoData/ResonantGeoData/blob/d69eda7c06cc42ddce74e4f69493c2b620a454d2/django-rgd-imagery/client/rgd_imagery_client/plugin.py#L105-L110

This is fine for the Python client we are shipping, but the new Vue front-end needs to do this as well and I think it'd be worthwhile to have a dedicated endpoint for this.

Thoughts, @mcovalt?

**Comment by mcovalt** [comment]
The STAC API only requires a unique ID per collection. Therefore both are needed in the STAC API. We have a unique ID across all collections so knowing the collection is unnecessary.

Since this is not part of the STAC API it should be documented separately from it. Perhaps this could be cleanly done with an [action](https://www.django-rest-framework.org/api-guide/viewsets/#marking-extra-actions-for-routing).
