### ISSUE TITLE
Tests for the ETL routine

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/ResonantGeoData#82]
We should write tests to verify the ETL routine (the readers under `geodata/models/`) work on CircleCI

**Comment by aashish24** [comment]
Daniel C is doing automated testing for the DANDI project as per Brian so perhaps it is worth talking to him

**Comment by banesullivan** [comment]
note to self: see work done in #107 on how to get started. Brian did an awesome job of setting up the testing infrastructure -- now it's up to me to start filling in the tests for the `geodata` app.

**Comment by banesullivan** [comment]
We will inevitably need to store some rasters and geometry for these tests. @brianhelba and @manthey, where might be the best place to store these data? Should we include these in the repository directly or maybe create another repo under @ResonantGeoData that we can clone during the tests?

**Comment by manthey** [comment]
I like what I've done in large_image and histomicsui.  Specifically, I have a python utility function that gets used in pytest functions.  It could be made into a fixture, if that were desired.  External data is hosted on data.kitware.com (though it could be hosted anywhere that is publicly accessible or accessible with stored credentials).

In the main repo, we store a key file which contains the sha512 hash of each data file we want from the external data store.  For instance, in large_image those sha512 files are in a test/data directory (https://github.com/girder/large_image/tree/master/test/data).  In the pytest function, these get used like `filePath = utilities.externaldata('data/sample.ome.tif.sha512')`.  This file is fetched and stored in a subdirectory of the tox directory.  If you run tox a second time, the hash of the file is checked and the file is only downloaded again if it has changed.

The utility function just uses `requests`.  In principal, it could use any service that can download a file based on a hash value.

This allows stored large test files, since they aren't in the repo.  GitHub limits file size to 100Mb.  There is git-lfs, but that costs per download after some threshold.

**Comment by brianhelba** [comment]
I think Git LFS is the best option. Do you think we'll exceed [GitHub's limits](https://docs.github.com/en/github/managing-large-files/about-storage-and-bandwidth-usage) in our initial usage? I'd hope that if only for test performance, we'd keep the sample raster files as small as possible.

To be fair, Git LFS has a decent number of flaws and annoyances, but I think it's the most generally supported and most resilient option.

**Comment by brianhelba** [comment]
@banesullivan I can set up the Git LFS infrastructure in this repo, such that we have a dedicated directory to commit test files. We should just resolve the question about expected size before committing to that route.

**Comment by manthey** [comment]
Please don't set up Git LFS.  1 Gb is tiny.  I don't know that we'll have a file greater than that in size, but for other projects I've had test files that are greater than 100 Mb.  With such a file, you can run at most ten tests a month.

**Comment by brianhelba** [comment]
Do we have an estimate of file size? Can we allocate budget to purchase extra storage from GitHub? Trying to maintain a `data.kitware.com`-based external data solution is a significantly greater labor investment than LFS. I wonder where the break-even point is going to be.

**Comment by manthey** [comment]
We already have a solution that "just works" using data.kitware.com.  Managing Git-LFS takes effort, too.  Estimating file sizes, dealing with billing, etc. takes labor investment.  I don't see a scenario where Git-LFS is ever cheaper in terms or labor.

**Comment by banesullivan** [comment]
How about using [pooch](https://github.com/fatiando/pooch) to manage our downloads and store the data on data.kitware.com while tracking the sha here?

Another thing, we may be able to get by with example data files each less than 50MB for a while. I can drastically downsample some Landsat imagery to something low resolution and just use that as a base test case for a while. After all, the goal is to test the ETL routines which mostly only look at the file header anyways.

**Comment by manthey** [comment]
pooch isn't a bad solution.  It, too, just uses `requests`.  It stores things in `~/.cache/pooch`, which is less isolated than a project's tox directory, but still fine.  We'd end up doing something like:

```
hashvalue = <128 character sha512 hexadecimal hash>
dkc = 'https://data.kitware.com/api/v1/file/hashsum/sha512/{hashvalue}/download'

pooch.retrieve(url=dkc.format(hashvalue=datafile), known_hash=f'sha512:{hashvalue}')
```

In large_image, the hashvalues for test files are stored as individual files (since it is easy to download such files from data.kitware.com), but instead we could have a general test utility file with a pooch registry.

@brianhelba What is your opinion?

For reference, I've got a test set of files that shows off some transformation issues where the total file size is hundreds of Mbytes.  I can probably use GDAL to transform these so they are still mostly equivalent tests and much smaller.
